# Generated by Django 4.2.2 on 2023-06-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('horas', models.IntegerField(null=True)),
                ('profesor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.curso'),
        ),
    ]
